### ISSUE TITLE
remove `unproven` flag

### ISSUE THREAD

**Issue by burrbull** [rust-embedded/svd#116]
Encoding works fine as for me.

I think we should prove it and remove `unproven` option.

Alternative:
Split this crate on several like `svd-base`, `svd-parser`, `svd-encoder`, `svd-utils`, tests.

**Comment by MarcoIeni** [comment]
> I think we should prove it and remove unproven option.

This means writing some tests, right? :)

In my project I added a test in which I test this library.
In the test I decode an xml, I encode it and then I decode it again.
The test asserts that the two decoded xml are equal.
Here is the test:
https://github.com/MarcoIeni/svdtools/blob/riir/tests/svd_parser.rs

Maybe we could start by writing a (integration?) test like this.
