### ISSUE TITLE
Incorrect names in SVDs

### ISSUE THREAD

**Issue by burrbull** [rust-embedded/svd#127]
Many Fujitsu and Freescale SVDs have incorrect enumerated value names that start with digit like:
```
                <enumeratedValue>
                  <name>0</name>
                  <description>Configured interrupt is not detected.</description>
                  <value>#0</value>
                </enumeratedValue>
```
For now `svd2rust` just adds `_` prefix.
But `check_name` blocks this:
https://github.com/rust-embedded/svd/blob/1d0833cd0ebe8f527767bc70709b684d6195f418/src/svd/enumeratedvalue.rs#L90

What should we do:
1. Remove this validation check.
2. Add `_` prefix during parsing.
3. Ignore incorrect files.
4. Allow digit on start of name.

cc @therealprof  @Emilgardis

**Comment by Emilgardis** [comment]
This validation is be default disabled now, to enable it, specify `[dependencies.svd] features = ["strict"]`

I want to move this to run-time instead, but this should suffice for now.
