### ISSUE TITLE
solve rust 1.36.0 clippy warnings

### ISSUE THREAD

**Issue by MarcoIeni** [rust-embedded/svd#135]
Once we do this we can enable clippy in the CI:

 https://github.com/rust-embedded/svd/blob/8a8b7a784f3c3cc9a0b14cdf25131682dc862fc2/.github/workflows/clippy.yml#L18-L21

**Comment by brainstorm** [comment]
I'm curious about the rationale behind bumping up (or not) the MSRV for this crate... wouldn't it make sense to require at least Rust 1.4x in this time and age? We're almost in 2021 ;)

/cc @burrbull

**Comment by burrbull** [comment]
https://github.com/rust-embedded/wg/pull/523

**Comment by Emilgardis** [comment]
Basically, we should always check current stable, and if a bump is needed, we bump MSRV
