### ISSUE TITLE
Proposal: struct instead of enum for arrays

### ISSUE THREAD

**Issue by burrbull** [rust-embedded/svd#164]
Instead of enum:
```rust
pub enum Register {
    /// A single register.
    Single(RegisterInfo),
    /// An array of registers.
    Array(RegisterInfo, DimElement),
}
```
I propose to use struct:
```rust
struct Register {
    info: RegisterInfo,
    dim: Option<DimElement>,
}
```
where `dim: None` corresponds to `Register::Single`.
The main goal is to simplify serialize/deserialize.

cc @Emilgardis  @therealprof  @adamgreig

**Comment by Emilgardis** [comment]
It would also be possible to do this with

```rust
#[cfg_attr(
    feature = "serde",
    derive(serde::Serialize, serde::Deserialize),
    serde(untagged)
)]
pub enum Register {
    /// A single register.
    Single {
        /// Register information
        info: RegisterInfo,
    },
    /// An array of registers.
    Array {
        /// Register information
        info: RegisterInfo,
        /// Array dim
        dim: DimElement,
    },
}
```

I wonder which one is the best

**Comment by burrbull** [comment]
> It would also be possible to do this with
> 
> ```rust
> #[cfg_attr(
>     feature = "serde",
>     derive(serde::Serialize, serde::Deserialize),
>     serde(untagged)
> )]
> pub enum Register {
>     /// A single register.
>     Single {
>         /// Register information
>         info: RegisterInfo,
>     },
>     /// An array of registers.
>     Array {
>         /// Register information
>         info: RegisterInfo,
>         /// Array dim
>         dim: DimElement,
>     },
> }
> ```
> 
> I wonder which one is the best

Unfortunately the result is different from I expect.
![изображение](https://user-images.githubusercontent.com/3072754/141054853-fed92a16-903f-42b9-ad11-85dd836fb653.png)

**Comment by burrbull** [comment]
I can take identical result with:
```rust
#[derive(Clone, Debug, PartialEq)]
#[cfg_attr(
    feature = "serde",
    derive(serde::Serialize, serde::Deserialize),
    serde(untagged)
)]
pub enum Register {
    /// A single register.
    Single(RegisterInfo),
    /// An array of registers.
    Array(RegisterArray),
}

#[derive(Clone, Debug, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
/// ...
pub struct RegisterArray {
    #[cfg_attr(feature = "serde", serde(flatten))]
    /// ...
    pub dim: DimElement,
    #[cfg_attr(feature = "serde", serde(flatten))]
    /// ...
    pub info: RegisterInfo,
}
```
But does this make sense?

**Comment by burrbull** [comment]
Let's just merge #173 instead.

**Comment by Emilgardis** [comment]
The reason for the difference is the ordering, placing dim before info in the enum struct would solve that.

Does

**Comment by Emilgardis** [comment]
Ah, my bad, I see the issue now. Too bad, I dont think there is a good way to solve this with current serde features
