### ISSUE TITLE
Add public constructors for Peripheral et al

### ISSUE THREAD

**Issue by japaric** [rust-embedded/svd#60]
Now svd-parser has encoding functionality but there are no public constructor for Peripheral et al so you can't use the encoding functionality, unless you have already parsed some SVD file.

cc @ryankurte @Emilgardis

**Comment by burrbull** [comment]
What is the point of `_extensible`?

**Comment by MarcoIeni** [comment]
Isn't this solved by #115?

**Comment by burrbull** [comment]
Yes.
